# Generated by Django 3.2.11 on 2023-02-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50, null=True)),
                ('confirm_password', models.CharField(max_length=50, null=True)),
                ('usertype', models.CharField(max_length=10, null=True)),
                ('pno', models.CharField(max_length=255, null=True)),
                ('addr', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
