# Generated by Django 3.2.11 on 2023-02-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_land'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=50, null=True)),
                ('owner_email', models.CharField(max_length=50, null=True)),
                ('owner_number', models.CharField(max_length=255, null=True)),
                ('land_area', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('landmark', models.CharField(max_length=200, null=True)),
                ('cost_unit', models.PositiveIntegerField(null=True)),
                ('photo', models.FileField(default='None', upload_to='photos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Land',
        ),
    ]
