# Generated by Django 4.1.5 on 2023-03-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_auto_20230217_1752"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landdetails",
            name="land_area",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
