# Generated by Django 4.1.5 on 2023-03-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_landdetails_land_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landdetails",
            name="photo",
            field=models.FileField(default="None", upload_to="static/images/"),
        ),
    ]
