# Generated by Django 4.1.5 on 2023-03-01 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_landdetails_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.PositiveIntegerField()),
                ("total_land", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(default="pending", max_length=10, null=True),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.register"
                    ),
                ),
                (
                    "land",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.landdetails",
                    ),
                ),
            ],
        ),
    ]
