# Generated by Django 4.1.5 on 2023-03-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_landregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="landregistration",
            name="pdf_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
